eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**, /api/v1/admin/**

        - id: projects
          uri: lb://project-service
          predicates:
            - Path=/api/v1/projects/**
          filters:
            - AuthenticationFilter

        - id: tasks
          uri: lb://task-service
          predicates:
            - Path=/api/v1/tasks/**
          filters:
            - AuthenticationFilter

        - id: comments
          uri: lb://comment-service
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - AuthenticationFilter

        - id: attachments
          uri: lb://attachment-service
          predicates:
            - Path=/api/v1/attachments/**
          filters:
            - AuthenticationFilter
