eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/user/**, /api/v1/admin/**

        - id: projects
          uri: lb://project-service
          predicates:
            - Path=/api/v1/projects/**
          filters:
            - AuthenticationFilter

        - id: users
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter


management:
  tracing:
    sampling:
      probability: 1.0