spring:
  application:
    name: attachment-service

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8030

application:
  config:
    tasks-url: http://localhost:8222/api/v1/tasks

management:
  tracing:
    sampling:
      probability: 1.0