spring:
  application:
    name: comment-service
  data:
    mongodb:
      username: yusuf
      password: yusuf
      host: localhost
      port: 27017
      database: comment
      authentication-database: admin

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8040

application:
  config:
    tasks-url: http://localhost:8222/api/v1/tasks

management:
  tracing:
    sampling:
      probability: 1.0